import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { GetServerSideProps } from "next/types";
import Image from "next/image";
import Link from "next/link";
import HomePage from "@/src/components/home/home-page";

export type EventCategory = {
  id: string;
  title: string;
  description: string;
  image: string;
};

export default function Home({ categories }: { categories: EventCategory[] }) {
  return (
    <>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage categories={categories} />
    </>
  );
}

//Runs on server only, is async because you need to fetch data
//On Every client request, the data is fetched new
export const getServerSideProps: GetServerSideProps = async () => {
  const eventData = await import("./../data/data.json");
  return {
    props: {
      categories: [...eventData.events_categories],
    },
  };
};
